server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  elasticsearch:
    rest:
      uris: http://192.168.198.128:9200
  jackson:
    default-property-inclusion: non_null  #springmvc返回数据到前端（@ResponseBody）默认使用的序列化工具是jackson;属性值为空的属性不返回。
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.198.128
    port: 5672
    virtual-host: /zhangsan
    username: zhangsan
    password: zhangsan
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
