server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  redis:
    host: 192.168.198.128
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart?characterEncoding=utf8&useSSL=false
    username: root
    password: root
# 声明式异步的线程池配置
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.198.128
    virtual-host: /zhangsan
    username: zhangsan
    password: zhangsan
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual


feign:
  sentinel:
    enabled: true

jwt:
  pubKeyPath: F:\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
  expire: 8640000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto