server:
  port: 18085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_oms?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.198.128
  rabbitmq:
    host: 192.168.198.128
    virtual-host: /zhangsan
    password: zhangsan
    username: zhangsan
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.oms.entity