server:
  port: 18088

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1

  redis:
    host: 192.168.198.128
feign:
  sentinel:
    enabled: true

thread:
  pool:
    coreSize: 100
    maxSize: 500
    keepAlive: 60
    blockingQueueSize: 2000